### ISSUE TITLE
.desktop only accepts PNG icon 

### ISSUE THREAD

**Issue by cibersheep** [Jujuyeh/webapp-creator#1]
Add bool svgicon to insertDesktop?

**Comment by Jujuyeh** [comment]
Added SVG support on insertDesktop. See `png` boolean under insertDesktop paragraph in the Wiki. [#6c57ad1](https://github.com/Jujuyeh/webapp-creator/commit/6c57ad1936fe517b67207cb586422bd9ec164cfb)
[#ffde062](https://github.com/Jujuyeh/webapp-creator/commit/ffde06286629eef9f2f16f641d00e9becbb517a5)
