### ISSUE TITLE
Update Ogra's Container

### ISSUE THREAD

**Issue by Jujuyeh** [Jujuyeh/webapp-creator#12]
We should switch to `Ubuntu.Web` to offer a better experience.

**Comment by mateosalta** [comment]
https://code.launchpad.net/~mateo-salta/+junk/alternate-webapp-container-youtube Ive been putting some updates into ogra's container, keeping the versions bumped.

Added themeable progress bar, fixed the fullscreen issue, some context menu items, you can pull some of these bits in if you wish.

**Comment by Jujuyeh** [comment]
Thank you very much for the contribution, this will help Webapp Creator a lot. Would you like to help us automate the creation and customization of new circles in the webapp? If so, contact me on telegram at @Jujuyeh .

(Your Twitter and Youtube webapps were what made us decide to add customizable Ogra webapps ❤️)

**Comment by mateosalta** [comment]
A lot of updates are in, I would still like to get it on par with the webcontianer. 

Wants:
- slide overlay page for external links
- Javascript confirmation button popup (try clearing a recent search in google, as well as other dialogs)
- Crash reload "sad page" (youtube videos seem to crash for uknown reason)
- complete context menu

**Comment by mateosalta** [comment]
#24
