### ISSUE TITLE
Qml becomes unresponsive after pressing «Create app» (after runnig C++ code)

### ISSUE THREAD

**Issue by CesarHerreraG** [Jujuyeh/webapp-creator#14]
In a BQ E4.5 with UBports OTA 15.04 r1
When it appears the share apps screen it doesn't show file manager. It is not possible to continue. I stop the program and get the click file from .cache/webapp-creator.jujuyeh.

**Comment by cibersheep** [comment]
As reported by @Pgcor same behaviour happens: app works until content-hub (it happens with other page pushed to main stack after "create app" button is pressed).

Both users have problems with File Manager not showing. Nothing to do with webapp-creator I think.

http://paste.ubuntu.com/25310920/

**Comment by alexanderisme** [comment]
I've got the freeze problem on sharing as well ! i.e. when the create app button ist pressed, you cannot do anything (if you click on an app you can't select it, if you click on the back button it does not work... And you can't scroll down).
I use a BQ E4.5 with the canonical image (OTA 15).
But in the list of apps there is the file manager app! My File manager version is 0.4.562

If you have any questions/specifications for this bug let me know ;)
Alexander

**Comment by cibersheep** [comment]
Ok. The problem seams to be calling the c++ code after pressing «Create webapp» blocks the QML code but only with e5 and e4.5

**Comment by cibersheep** [comment]
Bug spotted: All C++ code should run through QProcess and not "directly".
Duties:
 - update all functions except already working (genClick and clearTmp) to run as a QProcess

**Comment by alexanderisme** [comment]
I don't know if this information can help: I have tried to create a webapp and just after having clicked on the creation button I clicked (but really quickly !) on where the file manager icon will appear... And it worked ! So it's a little trick in order to already use your app ;) Maybe this information can help to know more about the reason it freezes !

**Comment by cibersheep** [comment]
That's really cool. Actually it works but you only have one shot.
For now, you can access to the created click through File Manager. You must tap on options and show hidden files and navigate to .cache/webapp-creator.jujuyeh/ and you'll find all the clicks there

**Comment by cibersheep** [comment]
Fixed in v1.1
