### ISSUE TITLE
[SPANISH] Install/save option

### ISSUE THREAD

**Issue by gnulinuxuser** [Jujuyeh/webapp-creator#20]
Estoy  tratando de crear una web-app, pero cuando trato de instalar o guardar. No pasa nada.
Me dirijo a la ruta donde supuestamente se guarda la aplicación "name.click"    pero no hay nada.  la trato de hacer share. Y nada.   trato de subirla a openstore.   y me dice, que me asegure que es una aplicación  click

**Comment by Jujuyeh** [comment]
Cuando presionas "Instalar o Guardar" debería aparecer una pantalla con unas cuantas apps como opcienes. Si seleccionas **OpenStore**, **instalará** la webapp en el dispositivo; si seleccionas **Gestor de Archivos**, podrás elegir dónde **guardar** la webapp. Todo ello suponiendo que se han llenado los campos de información correctamente. Si aun siguiendo estos pasos sigue sin crear o guardar correctamente la webapp, no dudes en avisar por aquí.

**Comment by gnulinuxuser** [comment]
Cuando presionó instalar o guardar, tengo 2 opciones.
Openstore y device

Openstore no me deja, siempre me dice que me asegure que el dile es .click

Device, selecciono la Rita predeterminada y nada, selecciono donde quiero que se guarde y tampoco.

Al crear la webapps, ya he seleccionada la poción de orca,ogra.... Perdón no recuerdo muy bien el nombre, pero el resultado es el mismo.

**Comment by gnulinuxuser** [comment]
Revisado..  toda la info. A Sido llenado correctamente. Mismo resultado
Mi dispositivo es un Nexus 5 con UT ( 15.04 ) from UBPorts

**Comment by cibersheep** [comment]
Hola. Podrías enviar el log?
Supongo que estás usando la versión 1.1 del Wepapp Creator, ¿no?
Gracias

**Comment by gnulinuxuser** [comment]
Hola, ya he resuelto el problema... He creado mi primera web -app, gracias a ustedes.  

Solamente hice una actualización del sistema, y trate de nuevo y funciono.  quizás me faltaban  algunos paquetes o dependencias.
Mi web-app ya esta en openstore ( xda )   Gracias.

**Comment by cibersheep** [comment]
Genial. Felicidades
