### ISSUE TITLE
lowercase app name must be more than one character

### ISSUE THREAD

**Issue by mateosalta** [Jujuyeh/webapp-creator#25]
Ran into a bug, where if you name your app with the "lowercase app name" being only one letter, it will create a click that installs a webapp that fails to launch, with very little errors to figure out what is going on.

**Comment by cibersheep** [comment]
Interesting.
We should add a check system for that... @Jujuyeh ?

**Comment by Jujuyeh** [comment]
That's strange... Anyway, i will add a function that checks that on the backend. @cibersheep add it to the field on the frontend.

**Comment by mateosalta** [comment]
https://github.com/mateosalta/webapp-creator/commit/40d42ea5e5b3e8c8451c51a550d276ac747aed83
